### ISSUE TITLE
Wrong Workforce Calculation

### ISSUE THREAD

**Issue by Quozar** [Ocelot1210/X4_ComplexCalculator#176]
Hi,

at first thx for the great tool.

Adding habitions get to much workforce percentage it goes up to 4400% on Energy Cells, makes it complicated to find the min-max amount of modules. Water got me 5219% efficiency.

I use v3.1.4. and import from a vanilla save game.

Idk if it has anything to do with language but my game language is German.

Oh, and there is a "Game Hall" module. I lack for the correct translation. But if I export the url to the website station calculator this modul prevent the complex to show up. I guess this modul is not listed in that calculater. 
Just to notify if someone has that problem and could not find the cause.

thx

**Comment by Ocelot1210** [comment]
Thank you for contacting me with your issue.

Please send me the plan (.x4 file) with the problem so that I can investigate.

I have confirmed the issue with the URL export and will correct this issue.

**Comment by Quozar** [comment]
I just created a water production with 4 modules and habitats, auto added the rest and adjust the workforces in the settings tab.
Unfortunately, I can't provide a screenshot in english because the game is german and so is the database.

[water.zip](https://github.com/Ocelot1210/X4_ComplexCalculator/files/11360678/water.zip)
![water](https://user-images.githubusercontent.com/132140569/235337760-3cb8737f-bfdf-4646-bf4f-def64e57c5f4.png)

**Comment by Ocelot1210** [comment]
Based on the data you sent us, we investigated and found the issue.

## Cause:
Mistake in extracting data from X4 itself. (Omission of correction in #5)
There was an error in extracting additional effects during ware production (e.g., productivity gains by workers, sunlight in sectors, etc.),
calculation wrong such as this one occurred. 

details : https://github.com/Ocelot1210/X4_ComplexCalculator/issues/5#issuecomment-679129570


## Measures implemented this time:
#5 Implemented similar modifications.

---
A version has been released that fixes this issue.
Please follow the steps below to see if the issue has been resolved.

**[Step1]**
Please use one of the following methods to obtain the latest execution environment

- Click "Help(H)" -> "Check Update... " at complex calculator.
- Download the latest version [here](https://github.com/Ocelot1210/X4_ComplexCalculator/releases)

**[Step2]**
Follow the steps below to update the DB.
1. Launch X4 Complex Calculator.
1. Select File(F) → Update DB from the menu in the upper left corner of the window.
1. Select "Yes" in the confirmation message.
1. Select output options on the data extraction window.
1. Click the Export button.
1. After data extraction is complete, click the Close button.
1. Restart X4 Complex Calculator.

**[Step 3]**
Please let me know if the issue has been resolved using the data in question.

**Comment by Quozar** [comment]
Yes, thank you, the problem is solved. I got the same percentage as it is in game.
