### ISSUE TITLE
can`t update database

### ISSUE THREAD

**Issue by serik-energy** [Ocelot1210/X4_ComplexCalculator#186]
In complex calculator (ver3.1.7) can`t select config folder path and language. Export button also inactive.
![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/15052177/aaac72c7-4a11-4131-96eb-26fa39e34759)
![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/15052177/9fcc3c0f-a3e2-4a30-b1c0-7995fc795ae6)

Fixed it by downgrading to previous version of app (v3.1.6-b2). After extracting DB I updated app back to ver3.1.7 and it`s working fine.

Use windows 11 23H2, last steam ver. x4 foundation 7.00 public beta 3 (russian) without mods with all dlc

**Comment by Ocelot1210** [comment]
Thank you for contacting me regarding your issue.
I apologize for the inconvenience.

It appears that you are having trouble retrieving the Config folder for X4 in your environment.
The Config folder represents the folder that contains the X4 save data and the folder to which the construction plans are output.

The following two types of X4 Config folders are referenced by the calculator.
1. %USERPROFILE%\Documents\Egosoft\X4\(random number)\
2. %USERPROFILE%\Documents\Egosoft\X4\

If config.xml exists in any of these folders, it will be recognized as the correct Config folder and will be selectable on the screen.

[Requests]
What is your environment's config folder path?
It should be folder 1 or 2 as listed above.

**Comment by serik-energy** [comment]
Thank you for quick response.
My save folder path: %USERPROFILE%\Documents\Egosoft\X4(random number)\
But with fresh install only savegames located there, and config.xml file was missing.
After reseting game settings to default new config.xml file was genereted, and everything seems to work correct now.
Thank you for help, much appreciated.

![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/15052177/9a054ba4-0b7a-4888-8384-b01bac0fe791)
![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/15052177/64da46c8-e1fa-4d13-a02d-c765b9b727c2)

**Comment by Ocelot1210** [comment]
Thank you for contacting me with your results.
I am glad to hear that the problem has been resolved.
Please feel free to contact me if you have any further issues.
