### ISSUE TITLE
[Feature Request] Empire overview / station connections

### ISSUE THREAD

**Issue by maritz** [Ocelot1210/X4_ComplexCalculator#31]
It would be super helpful if one could somehow connect the outputs (sell) of stations to the inputs (buy) of other stations. So that if I have a few Microchip factories their microchips can be seen as used for the Claytronics Factories. And then when I add more Claytronics it shows that my Microchip factories can't keep up anymore.

To visualise it:
![image](https://user-images.githubusercontent.com/159633/90950131-1f7c2380-e44f-11ea-96a1-2b83defc160c.png)

**Comment by maritz** [comment]
I think a simple window that adds up *all* resource amount/h values from all opened up stations shouldn't be that much effort to implement, right? And that would basically be all I need.

Connecting stations one by one would be a lot more effort and ultimately not as useful, after some reflection on it.

**Comment by Ocelot1210** [comment]
I was a bit mistaken.
I thought I was going to connect the stations one by one.

I agree that it would be easier if I could just tally up the production of product from all the stations that are open.

My holidays are over, so it's hard to get a coherent time frame.
I'd like to find time to implement the feature little by little.


Thank you.

**Comment by Ocelot1210** [comment]
I've just released a version with additional features that were requested.
Please download the latest version of the execution environment from [here](https://github.com/Ocelot1210/X4_ComplexCalculator/releases).

Thank you.

**Comment by maritz** [comment]
Tested, works! 👍
